# Generated by Django 4.1 on 2022-09-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_invites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageemployee',
            name='to_role',
            field=models.CharField(default='Supervisor', max_length=50),
        ),
    ]
