# Generated by Django 4.1 on 2022-09-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_invites', '0002_storageemployee_to_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageemployee',
            old_name='to_role',
            new_name='for_role',
        ),
    ]
