# Generated by Django 4.1 on 2022-09-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
