# Generated by Django 4.1 on 2022-10-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employer',
            field=models.IntegerField(default=0),
        ),
    ]
