# Generated by Django 4.1 on 2022-10-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supervisor_of',
            field=models.IntegerField(default=0),
        ),
    ]
