# Generated by Django 4.1 on 2022-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_min', models.IntegerField()),
                ('y_min', models.IntegerField()),
                ('z_min', models.IntegerField()),
                ('x_max', models.IntegerField()),
                ('y_max', models.IntegerField()),
                ('z_max', models.IntegerField()),
                ('monitor_from', models.IntegerField()),
                ('monitor_to', models.IntegerField()),
                ('temperature_min', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
