# Generated by Django 4.1 on 2022-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='monitor_from',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='monitor_to',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='area',
            name='temperature_max',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='temperature_min',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
