# Generated by Django 4.1 on 2022-09-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_temperature',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
