# Generated by Django 4.1 on 2022-10-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provinces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=250)),
                ('district_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='provinces.province')),
            ],
        ),
    ]
