# Generated by Django 4.1 on 2022-10-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=250)),
                ('permission_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_permissions', to='entities.entity')),
            ],
        ),
    ]
