# Generated by Django 4.1 on 2022-10-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='permission_mission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mission_permissions', to='missions.mission'),
            preserve_default=False,
        ),
    ]
