# Generated by Django 4.1 on 2022-10-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('roles', '0002_alter_role_permissions'),
        ('permissions', '0002_permissions_permission_mission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Permission',
        ),
    ]
