# Generated by Django 4.1 on 2022-09-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(max_length=250)),
                ('storage_length', models.IntegerField()),
                ('storage_width', models.IntegerField()),
                ('storage_height', models.IntegerField()),
                ('storage_code', models.CharField(default=None, max_length=64)),
                ('storage_street', models.CharField(max_length=250)),
                ('storage_created', models.DateTimeField(auto_now_add=True)),
                ('storage_updated', models.DateTimeField(auto_now=True)),
                ('storage_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_storages', to='branches.branch')),
                ('storage_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_storages', to='districts.district')),
            ],
        ),
    ]
