# Generated by Django 4.1 on 2022-09-04 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_invite'),
        ('storages', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StorageEmployee',
        ),
    ]
