# Generated by Django 4.1 on 2022-09-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0003_delete_storageemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='storage_code',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
