# Generated by Django 4.1 on 2022-10-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=250)),
                ('branch_street', models.CharField(max_length=250)),
                ('branch_created', models.DateTimeField(auto_now_add=True)),
                ('branch_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
