# Generated by Django 4.1 on 2022-09-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        ('branches', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_branches', to='companies.company'),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_branches', to='districts.district'),
        ),
    ]
