# Generated by Django 4.1 on 2022-11-06 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_username', models.CharField(max_length=250)),
                ('station_password', models.CharField(max_length=250)),
                ('station_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_stations', to='storages.storage')),
            ],
        ),
    ]
