# Generated by Django 4.1 on 2022-10-30 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage_accesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageaccess',
            name='access_employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_employee_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storageaccess',
            name='access_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_accesses', to='storages.storage'),
        ),
    ]
