# Generated by Django 4.1 on 2022-10-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_length', models.IntegerField()),
                ('pallet_width', models.IntegerField()),
                ('pallet_height', models.IntegerField()),
                ('pallet_drawers', models.IntegerField()),
                ('pallet_x', models.IntegerField()),
                ('pallet_y', models.IntegerField()),
                ('pallet_z', models.IntegerField()),
                ('pallet_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_pallets', to='storages.storage')),
            ],
        ),
    ]
