# Generated by Django 4.1 on 2022-11-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='pallet_color',
            field=models.CharField(default='NONE', max_length=250),
        ),
    ]
