# Generated by Django 4.1 on 2022-10-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='pallet_drawers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
