# Generated by Django 4.1 on 2022-12-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_level',
            field=models.IntegerField(default=3),
        ),
    ]
