# Generated by Django 4.1 on 2022-10-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_role_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permissions',
            new_name='role_permissions',
        ),
    ]
