# Generated by Django 4.1 on 2022-10-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('branch_accesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchaccess',
            name='access_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accesses', to='branches.branch'),
        ),
    ]
