# Generated by Django 4.1 on 2022-10-28 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permissions', '0003_rename_permissions_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_persons', to='permissions.permission')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
