# Generated by Django 4.1 on 2022-11-08 04:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pallets', '0003_remove_pallet_pallet_x_remove_pallet_pallet_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('location_y', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('location_z', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('location_pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_locations', to='pallets.pallet')),
            ],
        ),
    ]
