# Generated by Django 4.1 on 2022-09-10 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_role', models.CharField(default='Supervisor', max_length=50)),
                ('access_from_owner', models.BooleanField(default=False)),
                ('access_accept', models.BooleanField(default=False)),
                ('access_created', models.DateTimeField(auto_now_add=True)),
                ('access_updated', models.DateTimeField(auto_now=True)),
                ('access_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to=settings.AUTH_USER_MODEL)),
                ('access_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_accesses', to='storages.storage')),
            ],
        ),
    ]
